In [8]:
#ZADANIE 2
import pandas as pd
import numpy as np

oryginalny_plik = 'wyniki ankieta.csv'
df = pd.read_csv(oryginalny_plik, encoding='cp1250', sep=';')

print("Dane wczytane poprawnie!")

Dane wczytane poprawnie!

In [9]:
#ZADANIE 2,3
nowe_kolumny = [f'p{i}' for i in range(1, len(df.columns) + 1)]
df.columns = nowe_kolumny

print("Nazwy kolumn po zmianie:")
print(df.columns.tolist())

Nazwy kolumn po zmianie:
['p1', 'p2', 'p3', 'p4', 'p5', 'p6', 'p7', 'p8', 'p9', 'p10', 'p11', 'p12', 'p13', 'p14', 'p15', 'p16', 'p17', 'p18', 'p19', 'p20', 'p21', 'p22', 'p23', 'p24', 'p25', 'p26', 'p27', 'p28', 'p29', 'p30', 'p31', 'p32', 'p33', 'p34', 'p35', 'p36', 'p37', 'p38', 'p39', 'p40', 'p41', 'p42', 'p43', 'p44', 'p45', 'p46', 'p47', 'p48', 'p49', 'p50', 'p51', 'p52', 'p53', 'p54', 'p55', 'p56', 'p57', 'p58', 'p59', 'p60', 'p61', 'p62', 'p63', 'p64']

In [10]:
#ZADANIE 4
liczba_nowych_wierszy = 100

losowe_wiersze = df.sample(n=liczba_nowych_wierszy, replace=True, random_state=42)
df = pd.concat([df, losowe_wiersze], ignore_index=True)

print(f"Dodano {liczba_nowych_wierszy} wierszy. Nowy rozmiar tabeli to: {df.shape}")

Dodano 100 wierszy. Nowy rozmiar tabeli to: (104, 64)

In [11]:
#ZADANIE 5
nazwa_koloru_grupy = 'czarny'
nazwa_nowego_pliku = f'{nazwa_koloru_grupy}.csv'

df.to_csv(nazwa_nowego_pliku, index=False)
print(f"Zapisano gotowy plik jako: {nazwa_nowego_pliku}")

Zapisano gotowy plik jako: czarny.csv

In [12]:
#ZADANIE 6
print("--- 1. df.head() - Podgląd pierwszych 5 wierszy ---")
display(df.head())

print("\n--- 2. df.tail() - Podgląd ostatnich 5 wierszy ---")
display(df.tail())

print("\n--- 3. df.sample(5) - Losowanie 5 wierszy z tabeli ---")
display(df.sample(5))

print("\n--- 4. df.info() - Typy danych, brakujące wartości, zużycie pamięci ---")
df.info()

print("\n--- 5. df.describe() - Statystyki opisowe dla kolumn numerycznych ---")
display(df.describe())

print("\n--- 6. df.nunique() - Liczba unikatowych wartości w kolumnach ---")
display(df.nunique())

print("\n--- 7. df['p1'].value_counts() - Częstotliwość występowania wartości ---")
display(df['p1'].value_counts())

--- 1. df.head() - Podgląd pierwszych 5 wierszy ---

,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,...,p55,p56,p57,p58,p59,p60,p61,p62,p63,p64
0,3.3.2026 18:53:06,M??czyzna,18 - 26,?rednie,zam??na / ?onaty,miasto do 10 000 mieszka?ców,do 3 000 z?otych,niepodobny do mnie,?rednio podobny do mnie,?rednio podobny do mnie,...,?rednio podobny do mnie,bardzo podobny do mnie,?rednio podobny do mnie,?rednio podobny do mnie,?rednio podobny do mnie,niepodobny do mnie,troch? podobny do mnie,niepodobny do mnie,?rednio podobny do mnie,niepodobny do mnie
1,3.3.2026 19:16:56,M??czyzna,18 - 26,?rednie,panna / kawaler,miasto powy?ej 100 000 mieszka?ców,Brak,podobny do mnie,bardzo podobny do mnie,niepodobny do mnie,...,bardzo podobny do mnie,podobny do mnie,bardzo podobny do mnie,zupe?nie niepodobny do mnie,bardzo podobny do mnie,niepodobny do mnie,podobny do mnie,podobny do mnie,bardzo podobny do mnie,bardzo podobny do mnie
2,3.9.2026 13:22:41,M??czyzna,18 - 26,?rednie,panna / kawaler,miasto powy?ej 100 000 mieszka?ców,do 3 000 z?otych,?rednio podobny do mnie,troch? podobny do mnie,?rednio podobny do mnie,...,?rednio podobny do mnie,niepodobny do mnie,podobny do mnie,troch? podobny do mnie,?rednio podobny do mnie,?rednio podobny do mnie,?rednio podobny do mnie,podobny do mnie,troch? podobny do mnie,troch? podobny do mnie
3,3.9.2026 13:26:09,M??czyzna,18 - 26,zawodowe,panna / kawaler,miasto powy?ej 100 000 mieszka?ców,do 3 000 z?otych,troch? podobny do mnie,troch? podobny do mnie,?rednio podobny do mnie,...,troch? podobny do mnie,troch? podobny do mnie,troch? podobny do mnie,niepodobny do mnie,troch? podobny do mnie,troch? podobny do mnie,troch? podobny do mnie,?rednio podobny do mnie,niepodobny do mnie,?rednio podobny do mnie
4,3.9.2026 13:22:41,M??czyzna,18 - 26,?rednie,panna / kawaler,miasto powy?ej 100 000 mieszka?ców,do 3 000 z?otych,?rednio podobny do mnie,troch? podobny do mnie,?rednio podobny do mnie,...,?rednio podobny do mnie,niepodobny do mnie,podobny do mnie,troch? podobny do mnie,?rednio podobny do mnie,?rednio podobny do mnie,?rednio podobny do mnie,podobny do mnie,troch? podobny do mnie,troch? podobny do mnie

--- 2. df.tail() - Podgląd ostatnich 5 wierszy ---

,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,...,p55,p56,p57,p58,p59,p60,p61,p62,p63,p64
99,3.3.2026 19:16:56,M??czyzna,18 - 26,?rednie,panna / kawaler,miasto powy?ej 100 000 mieszka?ców,Brak,podobny do mnie,bardzo podobny do mnie,niepodobny do mnie,...,bardzo podobny do mnie,podobny do mnie,bardzo podobny do mnie,zupe?nie niepodobny do mnie,bardzo podobny do mnie,niepodobny do mnie,podobny do mnie,podobny do mnie,bardzo podobny do mnie,bardzo podobny do mnie
100,3.3.2026 19:16:56,M??czyzna,18 - 26,?rednie,panna / kawaler,miasto powy?ej 100 000 mieszka?ców,Brak,podobny do mnie,bardzo podobny do mnie,niepodobny do mnie,...,bardzo podobny do mnie,podobny do mnie,bardzo podobny do mnie,zupe?nie niepodobny do mnie,bardzo podobny do mnie,niepodobny do mnie,podobny do mnie,podobny do mnie,bardzo podobny do mnie,bardzo podobny do mnie
101,3.9.2026 13:26:09,M??czyzna,18 - 26,zawodowe,panna / kawaler,miasto powy?ej 100 000 mieszka?ców,do 3 000 z?otych,troch? podobny do mnie,troch? podobny do mnie,?rednio podobny do mnie,...,troch? podobny do mnie,troch? podobny do mnie,troch? podobny do mnie,niepodobny do mnie,troch? podobny do mnie,troch? podobny do mnie,troch? podobny do mnie,?rednio podobny do mnie,niepodobny do mnie,?rednio podobny do mnie
102,3.3.2026 19:16:56,M??czyzna,18 - 26,?rednie,panna / kawaler,miasto powy?ej 100 000 mieszka?ców,Brak,podobny do mnie,bardzo podobny do mnie,niepodobny do mnie,...,bardzo podobny do mnie,podobny do mnie,bardzo podobny do mnie,zupe?nie niepodobny do mnie,bardzo podobny do mnie,niepodobny do mnie,podobny do mnie,podobny do mnie,bardzo podobny do mnie,bardzo podobny do mnie
103,3.3.2026 18:53:06,M??czyzna,18 - 26,?rednie,zam??na / ?onaty,miasto do 10 000 mieszka?ców,do 3 000 z?otych,niepodobny do mnie,?rednio podobny do mnie,?rednio podobny do mnie,...,?rednio podobny do mnie,bardzo podobny do mnie,?rednio podobny do mnie,?rednio podobny do mnie,?rednio podobny do mnie,niepodobny do mnie,troch? podobny do mnie,niepodobny do mnie,?rednio podobny do mnie,niepodobny do mnie

--- 3. df.sample(5) - Losowanie 5 wierszy z tabeli ---

,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,...,p55,p56,p57,p58,p59,p60,p61,p62,p63,p64
28,3.9.2026 13:26:09,M??czyzna,18 - 26,zawodowe,panna / kawaler,miasto powy?ej 100 000 mieszka?ców,do 3 000 z?otych,troch? podobny do mnie,troch? podobny do mnie,?rednio podobny do mnie,...,troch? podobny do mnie,troch? podobny do mnie,troch? podobny do mnie,niepodobny do mnie,troch? podobny do mnie,troch? podobny do mnie,troch? podobny do mnie,?rednio podobny do mnie,niepodobny do mnie,?rednio podobny do mnie
53,3.3.2026 19:16:56,M??czyzna,18 - 26,?rednie,panna / kawaler,miasto powy?ej 100 000 mieszka?ców,Brak,podobny do mnie,bardzo podobny do mnie,niepodobny do mnie,...,bardzo podobny do mnie,podobny do mnie,bardzo podobny do mnie,zupe?nie niepodobny do mnie,bardzo podobny do mnie,niepodobny do mnie,podobny do mnie,podobny do mnie,bardzo podobny do mnie,bardzo podobny do mnie
12,3.9.2026 13:22:41,M??czyzna,18 - 26,?rednie,panna / kawaler,miasto powy?ej 100 000 mieszka?ców,do 3 000 z?otych,?rednio podobny do mnie,troch? podobny do mnie,?rednio podobny do mnie,...,?rednio podobny do mnie,niepodobny do mnie,podobny do mnie,troch? podobny do mnie,?rednio podobny do mnie,?rednio podobny do mnie,?rednio podobny do mnie,podobny do mnie,troch? podobny do mnie,troch? podobny do mnie
44,3.9.2026 13:22:41,M??czyzna,18 - 26,?rednie,panna / kawaler,miasto powy?ej 100 000 mieszka?ców,do 3 000 z?otych,?rednio podobny do mnie,troch? podobny do mnie,?rednio podobny do mnie,...,?rednio podobny do mnie,niepodobny do mnie,podobny do mnie,troch? podobny do mnie,?rednio podobny do mnie,?rednio podobny do mnie,?rednio podobny do mnie,podobny do mnie,troch? podobny do mnie,troch? podobny do mnie
56,3.9.2026 13:22:41,M??czyzna,18 - 26,?rednie,panna / kawaler,miasto powy?ej 100 000 mieszka?ców,do 3 000 z?otych,?rednio podobny do mnie,troch? podobny do mnie,?rednio podobny do mnie,...,?rednio podobny do mnie,niepodobny do mnie,podobny do mnie,troch? podobny do mnie,?rednio podobny do mnie,?rednio podobny do mnie,?rednio podobny do mnie,podobny do mnie,troch? podobny do mnie,troch? podobny do mnie

--- 4. df.info() - Typy danych, brakujące wartości, zużycie pamięci ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 64 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   p1      104 non-null    object
 1   p2      104 non-null    object
 2   p3      104 non-null    object
 3   p4      104 non-null    object
 4   p5      104 non-null    object
 5   p6      104 non-null    object
 6   p7      104 non-null    object
 7   p8      104 non-null    object
 8   p9      104 non-null    object
 9   p10     104 non-null    object
 10  p11     104 non-null    object
 11  p12     104 non-null    object
 12  p13     104 non-null    object
 13  p14     104 non-null    object
 14  p15     104 non-null    object
 15  p16     104 non-null    object
 16  p17     104 non-null    object
 17  p18     104 non-null    object
 18  p19     104 non-null    object
 19  p20     104 non-null    object
 20  p21     104 non-null    object
 21  p22     104 non-null    object
 22  p23     104 non-null    object
 23  p24     104 non-null    object
 24  p25     104 non-null    object
 25  p26     104 non-null    object
 26  p27     104 non-null    object
 27  p28     104 non-null    object
 28  p29     104 non-null    object
 29  p30     104 non-null    object
 30  p31     104 non-null    object
 31  p32     104 non-null    object
 32  p33     104 non-null    object
 33  p34     104 non-null    object
 34  p35     104 non-null    object
 35  p36     104 non-null    object
 36  p37     104 non-null    object
 37  p38     104 non-null    object
 38  p39     104 non-null    object
 39  p40     104 non-null    object
 40  p41     104 non-null    object
 41  p42     104 non-null    object
 42  p43     104 non-null    object
 43  p44     104 non-null    object
 44  p45     104 non-null    object
 45  p46     104 non-null    object
 46  p47     104 non-null    object
 47  p48     104 non-null    object
 48  p49     104 non-null    object
 49  p50     104 non-null    object
 50  p51     104 non-null    object
 51  p52     104 non-null    object
 52  p53     104 non-null    object
 53  p54     104 non-null    object
 54  p55     104 non-null    object
 55  p56     104 non-null    object
 56  p57     104 non-null    object
 57  p58     104 non-null    object
 58  p59     104 non-null    object
 59  p60     104 non-null    object
 60  p61     104 non-null    object
 61  p62     104 non-null    object
 62  p63     104 non-null    object
 63  p64     104 non-null    object
dtypes: object(64)
memory usage: 52.1+ KB

--- 5. df.describe() - Statystyki opisowe dla kolumn numerycznych ---

,p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,...,p55,p56,p57,p58,p59,p60,p61,p62,p63,p64
count,104,104,104,104,104,104,104,104,104,104,...,104,104,104,104,104,104,104,104,104,104
unique,4,1,1,2,2,2,2,4,3,2,...,3,4,4,4,3,3,3,3,4,4
top,3.9.2026 13:26:09,M??czyzna,18 - 26,?rednie,panna / kawaler,miasto powy?ej 100 000 mieszka?ców,do 3 000 z?otych,troch? podobny do mnie,troch? podobny do mnie,?rednio podobny do mnie,...,?rednio podobny do mnie,troch? podobny do mnie,troch? podobny do mnie,niepodobny do mnie,?rednio podobny do mnie,niepodobny do mnie,troch? podobny do mnie,podobny do mnie,niepodobny do mnie,?rednio podobny do mnie
freq,31,104,104,73,83,83,77,31,56,77,...,46,31,31,31,46,48,52,52,31,31

--- 6. df.nunique() - Liczba unikatowych wartości w kolumnach ---

p1     4
p2     1
p3     1
p4     2
p5     2
      ..
p60    3
p61    3
p62    3
p63    4
p64    4
Length: 64, dtype: int64

--- 7. df['p1'].value_counts() - Częstotliwość występowania wartości ---

p1
3.9.2026 13:26:09    31
3.3.2026 19:16:56    27
3.9.2026 13:22:41    25
3.3.2026 18:53:06    21
Name: count, dtype: int64